#!/bin/bash

set -o errexit -o pipefail -o noclobber -o nounset

! getopt --test > /dev/null
if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
    echo 'I’m sorry, `getopt --test` failed in this environment.'
    exit 1
fi

OPTIONS=i:u:k:r:o:h
LONGOPTS=ip:,user:,key:,reversekey:,output:,help

! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
    exit 2
fi
eval set -- "$PARSED"

ip=n
user=n
key=n
reversekey=n
output=-
interface=$(ip -o -6 route show to default | awk '{print $5}')
while true; do
    case "$1" in
        -h|--help)
            echo "usage: arimg [-apc]
                    [-i|—-ip $(ip addr show $interface | grep global | grep inet6 | awk ‘{print $2}’)]
                    [-u|--user $(whoami)] [-k|-—key .ssh/id_rsa]
                    [-r|—-reversekey .ssh/reversekey_rsa]
                    [-o|—-output deploy.img] input"
            exit 1
            ;;
        -i|--ip)
            ip="$2"
            shift 2
            ;;
        -u|--user)
            user="$2"
            shift 2
            ;;
        -k|--key)
            key="$2"
            shift 2
            ;;
        -r|--reversekey)
            reversekey="$2"
            shift 2
            ;;
        -o|--output)
            output="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Programming error"
            exit 3
            ;;
    esac
done

if test "$#" -ne 1; then
  echo "
usage: arimg [-apc] [-i|--ip 127.0.0.2]
          [-u|--user spinup] [-k|--key .ssh/id_rsa]
          [-r|--reversekey .ssh/reversekey_rsa]
          [-o|--output deploy.img] input"
    exit
fi

echo " IP: $ip, User: $user, RSA Key: $key, Signal Key: $reversekey, Out: $output"
