---

keystodeploy:
  - name: System Ansible
    sshkey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsDyVu8nKM0hdH5LIHEikZtU4zdr9gAoxBTufj/hVCFfkWeHrAGXWSUH3h016+g41IAGZev0ucYQSDiL2T2VbU4q5OV/TzYzuOZ6mRppNltePsIQY0eWTBjA1ZnTy1JJJM8XumQEQt8h/4tfQ+EiVanmMoDNiRSb2lTFJ2kb+d4iYJYiyoWmqVjY313UoGbT+Z0Iu6X7byhRLGu3tpf8rT3cd3lAZRLsF2ZsBAeNBM0KJ7Wj4KMDHPHhhrHOFTDFJ+y7PZOXBXCkSqrB7d1YPJjycrqFIpj8+Op4bZCs+eBvDiHV0l9nWjC3nmFBg91Mb/l8WBwgVGEZeW+1r9ABRzPbv857iTmkCNdaHjrhctFIJm/Wx0RZ6o5ewxxkgyYgBK+i9+5IWe3ICbfQrCgEHIIl/unRUwO4TLqPzCiseCP2+0x9ggmaPCyXOsSs3TDVCI4KvwhMQspEkD5u0TVzHTX0JID763VvLBOydM1HtkRn1sHeQOxLIbww4Nzl2LsIc= 
