---
- hosts: all
  remote_user: ansible
  tasks:
    - name: 'Benutzer "spinup" entfernen'
      become: true
      user:
        name: spinup
        state: absent
        remove: yes

    - name: 'Gruppe "spinup" entfernen'
      become: true
      group:
        name: spinup
        state: absent

    - name: Reboot host
      shell: sleep 2 && /sbin/shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
    - name: Wait for host to come back up
      become: false
      wait_for_connection:
        delay: 15
        sleep: 2
        timeout: 120
